# Generated by Django 4.1.4 on 2023-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_options_articles_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='logo',
            field=models.ImageField(max_length=255, null=True, upload_to='./main/static/main/img'),
        ),
    ]
