# Generated by Django 4.1.4 on 2023-03-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='logo',
        ),
    ]
